import xml.etree.ElementTree as ET

file_path = r'c:\Users\fabio.dagostino\Desktop\RazorEnhanced-release-1.0\Razor\RazorEnhanced\UI\Strings.it.resx'

translations = {
    'MainForm.tabPage2.Text': 'Barra Statistiche',
    'MainForm.groupBox39.Text': 'Opacità',
    'MainForm.groupBox25.Text': 'Generale',
    'MainForm.lockToolBarCheckBox.Text': 'Blocca Barra',
    'MainForm.autoopenToolBarCheckBox.Text': 'Apri al Login',
    'MainForm.closeToolBarButton.Text': 'Chiudi',
    'MainForm.openToolBarButton.Text': 'Apri',
    'MainForm.groupBox4.Text': 'Layout',
    'MainForm.showtitheToolBarCheckBox.Text': 'Mostra Decime',
    'MainForm.label43.Text': 'Slot:',
    'MainForm.label41.Text': 'Dimensione:',
    'MainForm.showfollowerToolBarCheckBox.Text': 'Mostra Follower',
    'MainForm.showweightToolBarCheckBox.Text': 'Mostra Peso',
    'MainForm.showmanaToolBarCheckBox.Text': 'Mostra Mana',
    'MainForm.showstaminaToolBarCheckBox.Text': 'Mostra Stamina',
    'MainForm.showhitsToolBarCheckBox.Text': 'Mostra Vita',
    'MainForm.label2.Text': 'Stile:',
    'MainForm.groupBox26.Text': 'Conteggio Oggetti',
    'MainForm.label38.Text': '-1 per tutti',
    'MainForm.label37.Text': 'Nome:',
    'MainForm.toolboxcountClearButton.Text': 'Svuota Slot',
    'MainForm.toolboxcountTargetButton.Text': 'Ottieni Dati',
    'MainForm.label36.Text': 'Avviso:',
    'MainForm.toolboxcountHueWarningCheckBox.Text': 'Mostra Avviso',
    'MainForm.label35.Text': 'Colore:',
    'MainForm.label18.Text': 'Grafica:',
    'MainForm.tabPage3.Text': 'Griglia Magie',
    'MainForm.groupBox38.Text': 'Opacità',
    'MainForm.groupBox37.Text': 'Layout',
    'MainForm.label80.Text': 'Stile:',
    'MainForm.label53.Text': 'Slot O:',
    'MainForm.label49.Text': 'Slot V:',
    'MainForm.groupBox36.Text': 'Oggetto Griglia',
    'MainForm.label65.Text': 'Script',
    'MainForm.label44.Text': 'Bordo: ',
    'MainForm.label52.Text': 'Abilità/Magia:',
    'MainForm.label51.Text': 'Slot:',
    'MainForm.label45.Text': 'Gruppo:',
    'MainForm.groupBox35.Text': 'Generale',
    'MainForm.setSpellBarOrigin.Text': 'Imposta Origine',
    'MainForm.gridlock_CheckBox.Text': 'Blocca Griglia',
    'MainForm.gridopenlogin_CheckBox.Text': 'Apri al Login',
    'MainForm.gridclose_button.Text': 'Chiudi',
    'MainForm.gridopen_button.Text': 'Apri',
    
    # Other potential missing MainForm strings, since they were probably left English:
    'MainForm.groupBox8.Text': 'Chiave Master',
    'MainForm.hotkeyMasterClearButton.Text': 'Cancella',
    'MainForm.hotkeyMasterSetButton.Text': 'Imposta',
    'MainForm.label42.Text': 'Tasto:',
    'MainForm.groupBox28.Text': 'Generale',
    'MainForm.hotkeyMDisableButton.Text': 'Disabilita',
    'MainForm.hotkeyMEnableButton.Text': 'Abilita',
    'MainForm.hotkeyKeyMasterLabel.Text': 'Tasto ON/OFF: Nessuno',
    'MainForm.hotkeyStatusLabel.Text': 'Stato: Abilitato',
    'MainForm.hotkeypassCheckBox.Text': 'Passa Tasto a UO',
    'MainForm.hotkeyClearButton.Text': 'Cancella',
    'MainForm.hotkeySetButton.Text': 'Imposta',
    'MainForm.label39.Text': 'Tasto:',
    'MainForm.label79.Text': 'X',
    
    'MainForm.openchangelogButton.Text': 'Changelog',
    'MainForm.profilesCloneButton.Text': 'Clona',
    'MainForm.profilesRenameButton.Text': 'Rinomina',
    'MainForm.profilesUnlinkButton.Text': 'Scollega',
    'MainForm.profilesLinkButton.Text': 'Collega',
    'MainForm.profilelinklabel.Text': 'Collegato a: Nessuno',
    'MainForm.profilesDeleteButton.Text': 'Elimina',
    'MainForm.profilesAddButton.Text': 'Aggiungi',
    'MainForm.gameSize.Text': 'Forza Risoluzione:',
    'MainForm.rememberPwds.Text': 'Ricorda password',
    'MainForm.systray.Text': 'System Tray',
    'MainForm.taskbar.Text': 'Taskbar',
    'MainForm.label11.Text': 'Mostra in:',
    'MainForm.opacityLabel.Text': 'Opacità: 100%',
    'MainForm.label9.Text': 'Priorità Client:',
    'MainForm.remoteControl.Text': 'Abilita Controllo Remoto',
    'MainForm.ChkForUpdate.Text': 'Controlla Aggiornamenti',
    'MainForm.advertisementLink.Text': 'UO Eventine',
    'MainForm.advertisementDiscordLink.Text': 'Discord UO Eventine',
    
    'MainForm.label12.Text': 'Formato Immagine:',
    'MainForm.capNow.Text': 'Scatta Foto Ora',
    'MainForm.radioUO.Text': 'Solo UO',
    'MainForm.radioFull.Text': 'Schermo Intero',
    'MainForm.screenAutoCap.Text': 'Foto Automatica Morte',
    'MainForm.dispTime.Text': 'Includi Timestamp su immagini',
    'MainForm.videoRecStatuslabel.Text': 'Inattivo',
    'MainForm.label64.Text': 'Stato Rec:',
    'MainForm.groupBox40.Text': 'Riproduzione',
    'MainForm.videosettinggroupBox.Text': 'Impostazioni Video',
    'MainForm.label63.Text': 'Codec:',
    'MainForm.label62.Text': 'FPS: ',
    'MainForm.groupBox15.Text': 'File',
    
    'MainForm.DPStabPage.Text': 'Misuratore DPS',
    'MainForm.filtergroup.Text': 'Filtro',
    'MainForm.DPSMeterClearFilterButton.Text': 'Pulisci',
    'MainForm.DPSMeterApplyFilterButton.Text': 'Applica',
    'MainForm.label70.Text': 'Nome:',
    'MainForm.label69.Text': 'Seriale:',
    'MainForm.label68.Text': 'Danno Massimo:',
    'MainForm.label66.Text': 'Danno Minimo:',
    'MainForm.DPSMeterStatusLabel.Text': 'Inattivo',
    'MainForm.label67.Text': 'Stato:',
    'MainForm.DPSMeterPauseButton.Text': 'Pausa',
    'MainForm.DPSMeterStopButton.Text': 'Ferma',
    'MainForm.DPSMeterStartButton.Text': 'Avvia',
    'MainForm.DPSMeterClearButton.Text': 'Pulisci',
    'MainForm.label71.Text': 'Molti ringraziamenti anche allo sviluppatore di UO.DLL e ULTIMA.DLL',
    
    'MainForm.modifyToolStripMenuItem.Text': 'Modifica',
    'MainForm.addToolStripMenuItem.Text': 'Aggiungi',
    'MainForm.removeToolStripMenuItem.Text': 'Rimuovi',
    'MainForm.openToolStripMenuItem.Text': 'Apri',
    'MainForm.moveUpToolStripMenuItem.Text': 'Sposta Su',
    'MainForm.moveDownToolStripMenuItem.Text': 'Sposta Giù',
    'MainForm.moveToToolStripMenuItem.Text': 'Sposta In',
    'MainForm.flagsToolStripMenuItem.Text': 'Flags',
    'MainForm.loopModeToolStripMenuItem.Text': 'Modalità Ciclo',
    'MainForm.preloadToolStripMenuItem.Text': 'Precarica',
    'MainForm.waitBeforeInterruptToolStripMenuItem.Text': 'Attendi Prima Di Interrompere',
    'MainForm.autoStartAtLoginToolStripMenuItem.Text': 'Autostart al Login',
    'MainForm.playToolStripMenuItem.Text': 'Riproduci',
    'MainForm.stopToolStripMenuItem.Text': 'Ferma',
}

tree = ET.parse(file_path)
root = tree.getroot()

changed = 0
for data in root.findall('data'):
    name = data.get('name')
    if name in translations:
        value_tag = data.find('value')
        if value_tag is not None:
            value_tag.text = translations[name]
            changed += 1

tree.write(file_path, encoding='utf-8', xml_declaration=True)
print(f"Updated {changed} translations in Strings.it.resx")
