using System;

namespace TMRazorImproved.Shared.Enums
{
    /// <summary>
    /// Identificativi per le stringhe di localizzazione dell'applicazione.
    /// Basato sui valori originali di Razor per compatibilità con i file di lingua esistenti.
    /// </summary>
    public enum LocString : int
    {
        Null = 0,
        __Start = 1000,
        DeathStatus, BardMusic, DogSounds, CatSounds, HorseSounds, SheepSounds, SS_Sound, FizzleSound, Weather,
        DispCounters, RecountCounters, ClearAbility, SetPrimAb, SetSecAb, ToggleStun, ToggleDisarm, SettingAOSAb,
        AOSAbCleared, UndressAll, UndressHands, UndressLeft, UndressRight, UndressHat, UndressJewels, BandageSelf,
        BandageLT, UseBandage, DrinkHeal, DrinkCure, DrinkRef, DrinkNS, DrinkExp, DrinkStr, DrinkAg, NoBandages,
        NoItemOfType, DClickA1, ReTarget, Conv2DCT, SelTargAct, ProfileLoadEx, MacroItemOutRange, LiftA10,
        ConvLiftByType, MacroNoHold, EquipTo, DropA2, ConvRelLoc, DropRelA3, GumpRespB, CloseGump, MenuRespA1,
        MacroNoTarg, AbsTarg, ConvLT, ConvTargType, TargRelLocA3, LastTarget, TargetSelf, SetLT, TargRandRed,
        TargRandGrey, TargRandBlue, TargRandEnemy, TargRandFriend, TargRandNFriend, SayQA1, UseSkillA1, CastSpellA1,
        SetAbilityA1, DressA1, UndressA1, UndressLayerA1, WaitAnyMenu, WaitMenuA1, Edit, WaitAnyGump, WaitGumpA1,
        WaitTarg, PauseA1, WaitA3, LoadingA1, StopCurrent, PlayA1, PlayingA1, MacroFinished, InitError, IE_1, IE_2,
        IE_3, IE_4, IE_5, IE_6, IE_7, NoMemCpy, SkillChanged, InvalidAbrev, InvalidIID, InvalidHue, SelItem2Count,
        ProfileCorrupt, NoProp, CounterFux, NoAutoCount, CountLow, SelHue, TakeSS, TitleBarTip, RazorStatus1,
        SetSLUp, SetSLDown, SetSLLocked, ConfirmDelCounter, ProfLoadQ, ProfLoadE, NoDelete, EnterProfileName,
        ProfExists, DressName, DelDressQ, OutOfRangeA1, DelDressItemQ, TargUndressBag, UB_Set, ItemNotFound,
        KeyUsed, SaveOK, PacketLogWarn, Conv2Type, NewMacro, InvalidChars, MacroExists, MacroConfRec, DelConf,
        InsWait, InsLT, MoveUp, Down, RemAct, BeginRec, FileNotFoundA1, Confirm, FileDelError, NextRestart,
        PWWarn, NeedPort, QueueIgnore, ActQueued, QueueFinished, UseOnceAgent, AddTarg, AddContTarg, RemoveTarg,
        ClearList, TargItemAdd, TargCont, TargItemRem, ItemAdded, ItemRemoved, ItemsAdded, UseOnceEmpty,
        UseOnceStatus, UseOnceError, SellTotals, Remove, ContSet, Clear, PushDisable, PushEnable, SetHB, ClearHB,
        OrganizerAgent, Organizer, OrganizeNow, ContNotSet, NoBackpack, OrgQueued, OrgNoItems, ItemExists,
        AutoSearchEx, BuyTotals, BuyLowGold, EnterAmount, PrioSet, CurTime, CurLoc, UndressBagRange, UndressQueued,
        DressQueued, AlreadyDressed, ItemsNotFound, NoSpells, StealthSteps, StealthStart, ClearTargQueue,
        AttackLastComb, TQCleared, TargSetLT, LTSet, NewTargSet, TargNoOne, QueuedTS, QueuedLT, OTTCancel,
        TargByType, Scavenger, DeleteConfirm, SelSSFolder, HotKeys, HKSubOffset = 1249, Sell = 1301, Buy,
        InputReq, CommandList, UseHand, MustDisarm, ArmDisarmRight, ArmDisarmLeft, DropCur, SpellWeaving,
        ToggleHKEnable, HKEnabledPress, HKDisabledPress, HKEnabled, HKDisabled, WalkA1, AddTargType, LTOutOfRange,
        SellAmount, SnoopFilter, PackSound, InsIF, InsELSE, InsENDIF, SetAmt, Restock, RestockNow, RestockAgent,
        RestockTarget, InvalidCont, RestockDone, CancelTarget, NewerVersion, Reload, Save, LTGround, Resync,
        DismountBlocked, RecStart, VidStop, RecError, WrongVer, VideoCorrupt, ReadError, CatName, CantDelDir,
        CanCreateDir, CantMoveMacro, Friends, Reserved0 = 1350, Reserved1 = 1359, TargFriendAdd, TargFriendRem,
        FriendAdded, FriendRemoved, Constructs, InsFOR, InsENDFOR, NumIter, ClearScavCache, LastSpell, LastSkill,
        LastObj, AllNames, UseOnce, TargRandEnemyHuman, TargRandGreyHuman, TargRandInnocentHuman,
        TargRandCriminalHuman, TargRandCriminal, ForceEndHolding, RestartClient, ApplyOptionsRequired,
        LiftQueued, RestockQueued, StrChanged, DexChanged, IntChanged, LightFilter, HealPoisonBlocked,
        ClearDragDropQueue, StopNow, HealOrCureSelf, NextTarget, SetRestockHB, AddUseOnce, AttackLastTarg,
        EditTimeout, NoHold, NotAllowed, Allowed, NegotiateTitle = 1400, AllFeaturesEnabled, FeatureDescBase,
        NextCliloc = 1466, FeatureDisabled = NextCliloc, FeatureDisabledText, InsComment, AddFriend, RemoveFriend,
        MiniHealOrCureSelf, NoPatchWarning, Dismount, ToggleMap, TooFar, DragDropQueueFull, ToggleWarPeace,
        VetRewardGump, ForceSizeBad, ScavengerHB, RestockHBA1, UseOnceHBA1, SellHB, OrganizerHBA1, BadServerAddr,
        PartyAccept, PartyDecline, HarmfulTarget, BeneficialTarget, RazorFriend, PlayFromHere, Initializing,
        LoadingLastProfile, LoadingClient, WaitingForClient, RememberDonate, Welcome, Auto2D, Auto3D,
        AutoDetect, OpacityA1 = 1501, NewTimeout, NotAssigned, ChangeTimeout, EnterAName, Invalid, StaffOnlyItems,
        sStatsA1, DrinkApple, TargCloseRed, TargCloseGrey, TargCloseBlue, TargCloseEnemy, TargCloseFriend,
        TargCloseNFriend, TargCloseEnemyHuman, TargCloseGreyHuman, TargCloseInnocentHuman, TargCloseCriminalHuman,
        TargCloseCriminal, ProfileInUse, WaitingTimeout, NoCliLocMsg, NoCliLoc, BOD, LaunchBODAgent,
        NextTargetHumanoid, Mysticism = 1600, EnhancedMacroError = 1601, StaffOnlyNpcs, NewClipboardMacro = 1950,
        CopyClipboardMacro = 1951, DeerSounds, MacroRename, NewMacroVariable, TargCloseGreyMonster,
        TargCloseEnemyMonster, TargRandGreyMonster, TargRandEnemyMonster, CyclopTitanSounds, NextTargetEnemyHumanoid,
        UnableToOpenMacro, PauseCurrent, MacroPaused, MacroResuming, StunReady, StunSuccessful, StunDisabled,
        StunFailed, AllCorpses, AllMobiles, BullSounds, DragonSounds, SetSellAgentHotBag, AddUseOnceContainer,
        ChickenSounds, Reserved3, ScavengerEnableDisable, ScavengerSetHotBag, ScavengerAddTarget, GoldPerHotkey,
        EnterNewText, ImportFromPrevious, SetOrganizerHB, SetContainerLabel, AddToIgnore, RemoveFromIgnore,
        RazorIgnored, IgnoreAgent, PrevTarget, PrevTargetEnemyHumanoid, PrevTargetHumanoid, UseLastGumpResponse,
        SetContainerAlias, Interrupt, CaptureBod, DamageTracker, EnableHotkeys, DisableHotkeys, ClientDataMismatch,
        TargetRandom, TargCloseRedMonster, TargCloseRedHumanoid, TargClosest, TargRandomRedHuman,
        TargRandomRedMonster, TargRandomNFriendlyHuman, TargRandomNFriendlyMonster, TargRandomFriendlyHuman,
        TargRandomFriendlyMonster, TargRandomInnocentMonster, TargRandomCriminalMonster, TargClosestNFriendlyHuman,
        TargClosestNFriendlyMonster, TargClosestFriendlyHuman, TargClosestFriendlyMonster, TargClosestInnocentMonster,
        TargClosestCriminalMonster, NextTargetMonster, PrevTargetMonster, AddAllMobileFriends, AllCome, AllFollowMe,
        AllFollow, AllGuardMe, AllGuard, AllKill, AllStay, AllStop, PetCommands, Friend, StrChangeOverhead,
        DexChangeOverhead, IntChangeOverhead, SkillChangeOverhead, GrabItem, SetGrabItemHotBag, GrabItemTarget,
        GrabHB, NextTargetCriminalHumanoid, NextTargetMurdererHumanoid, NextTargetInnocentHumanoid,
        PrevTargetCriminalHumanoid, PrevTargetMurdererHumanoid, PrevTargetInnocentHumanoid, CriminalTargets,
        EnemyTargets, FriendlyTargets, GreyTargets, InnocentTargets, MurdererTargets, NonFriendlyTargets,
        NextTargetFriendlyHumanoid, NextTargetGreyHumanoid, NextTargetNonFriendlyHumanoid,
        PrevTargetFriendlyHumanoid, PrevTargetGreyHumanoid, PrevTargetNonFriendlyHumanoid, ToggleWar, TogglePeace,
        GHealOrCureSelf, SetLastBeneficial, SetLastHarmful, SetLTBene, SetLTHarm, TargClosestFriend,
        TargRandomFriend, NextTargetFriend, PrevTargetFriend, UseRightHand, UseLeftHand, InsertOverheadMessage,
        InsertWaitForTarget, AddAllHumanoidsAsFriends, NextTargetEnemyMonster, NextTargetCriminalMonster,
        NextTargetMurdererMonster, NextTargetInnocentMonster, PrevTargetCriminalMonster, PrevTargetMurdererMonster,
        PrevTargetInnocentMonster, NextTargetFriendlyMonster, NextTargetGreyMonster, NextTargetNonFriendlyMonster,
        PrevTargetEnemyMonster, PrevTargetFriendlyMonster, PrevTargetGreyMonster, PrevTargetNonFriendlyMonster,
        NewBeneficialTarget, NewHarmfulTarget, BirdSounds, AddAllMobilesTargetFilter,
        AddAllMobilesHumanoidTargetFilter, Season, Circle_9_Spells = 2100, Druid_Spells = 2120,
        Cleric_Spells = 2140, Last_Cleric_Spell = 2151, __End
    }
}
